### ISSUE TITLE
QR Code generator no longer works

### ISSUE THREAD

**Issue by sguha00** [expo/expo-preview-action#13]
### Description of the bug

Generating a QR code for a dev-client app is no returning and Error Forbidden: https://us-central1-exponentjs.cloudfunctions.net/generateQRCode/development-client?appScheme=instamenu&url=https://exp.host/@instamenu/instamenu-mobile/index.exp?release-channel=mobile-ime-779-api-mutation-to-create-cards&sdkVersion=42.0.0

### To Reproduce

The `EXPO_QR_CODE_URL` from the expo action is returning a URL that is returning "Error Forbidden"

#### Expected behavior

URL should display QR code

#### Actual behavior

URL is returning "Error Forbidden"

### Additional context

URLs were valid until today, 6/28/22

**Comment by jedahan** [comment]
Same issue. Funny thing is, if you try visiting the cloudfunctions.net url, it asks to sign into a google account

**Comment by ren1suyama** [comment]
Same here!

Seems `steps.publish.outputs.EXPO_QR_CODE_URL` nor `steps.preview.outputs.EXPO_PROJECT_URL` is not fetching the right URL when displaying the QR code on the PR.

As a temporary treatment, you can find the Expo QR code URL inside `Publish application` in the Job. However, I hope this issue gets solved soon for convenience.

![Screen Shot 2022-07-13 at 16 19 51](https://user-images.githubusercontent.com/108507461/178674476-8f6bae55-f3fe-4190-810b-7a5add803c55.png)

**Comment by tcdavis** [comment]
Hi all, I believe this issue has been resolved, but in case there is some sort of regional issue, could someone confirm for me? https://qr.expo.dev/development-client?appScheme=example&url=http%3A%2F%2Fexp.host%2F%40example%2Fapp this url should display a QR code

**Comment by sguha00** [comment]
> Hi all, I believe this issue has been resolved, but in case there is some sort of regional issue, could someone confirm for me? https://qr.expo.dev/development-client?appScheme=example&url=http%3A%2F%2Fexp.host%2F%40example%2Fapp this url should display a QR code

That link shows a QR code for me

**Comment by leonidkaida** [comment]
This link shows for me a QR code as well

**Comment by tcdavis** [comment]
Great, thanks!

**Comment by Pastromhaug** [comment]
Is this issue resolved? I'm still having the problem.  I'm getting a URL that starts with https://us-central1-exponentjs.cloudfunctions.net/generateQRCode/ instead of https://qr.expo.dev/ And it's showing `Error: Forbidden`. 

Manually changing the URL to use the latter prefix. Does the PR opened by @piotrski needs to be merged? https://github.com/expo/expo-preview-action/pull/15

**Comment by Pastromhaug** [comment]
amazing! thanks @jonsamp. Can we get a new release as well? The last one, 1.2.1, came out on Feb 7 this year.

**Comment by Nicomalacho** [comment]
Hey, I just set up this, and I'm getting this URL https://us-central1-exponentjs.cloudfunctions.net/ for the QR

How can I set the version of this action in the CI? so it uses the latest fix?

**Comment by Nicomalacho** [comment]
nvm just found the answer 
```
- name: Expo Preview Action
  uses: expo/expo-preview-action@v1.2.2
