### ISSUE TITLE
EAS support

### ISSUE THREAD

**Issue by brookemitchell** [expo/expo-preview-action#7]
Maybe this is a feature more for the eas-cli, if so please close. I'd love to be able to trigger a build and have a QR code for my code reviewers to pull up, right now if we use eas they have to find the build in the expo builds list.

Not a biggie but I really like the idea of this workflow. Let us know if you plan to support generating a build qr code for eas buiulds

**Comment by Maker-Mark** [comment]
@brookemitchell What's stopping you from using this action's output with the QR code/project publish page for testing? That's what I'm doing, and it works fine!
